### ISSUE TITLE
COPY REPO, YOU SHOULD READ THE LICENSE!

### ISSUE THREAD

**Issue by Alro10** [cuge1995/awesome-time-series#7]
Hello.

Please if you have some kind of respect please comment bellow and do not close the issue before we not resolve it. First of all, you repo is only a copy of mine, https://github.com/Alro10/deep-learning-time-series, so let me give you a simple example: if you make a paper you have to cite the references, right? so in this case you must cite my repo also it is mandatory to read the license, here: 

https://github.com/Alro10/deep-learning-time-series/blob/master/LICENSE

OPEN SOURCE doesn’t mean you copy all the code, readme file or script, and paste, you need to cite and write an explicit reference, other possible solution is to make a fork and contribute to the original main repository. Did you understand?

Regards,

**Comment by cuge1995** [comment]
actually, I have changed a lot, and you are the contributor too.
